-- Run in Supabase SQL Editor to enable gacha pull history.
-- Table: user_gacha_pulls (logs each pull for "History" on the Gacha page)

-- Table may already exist; ignore errors if re-running.
CREATE TABLE IF NOT EXISTS user_gacha_pulls (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pool_id bigint NOT NULL REFERENCES gacha_pools(id) ON DELETE CASCADE,
  reward_type text NOT NULL,
  pull_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_gacha_pulls_user_id ON user_gacha_pulls(user_id);
CREATE INDEX IF NOT EXISTS idx_user_gacha_pulls_pull_at ON user_gacha_pulls(pull_at DESC);

COMMENT ON TABLE user_gacha_pulls IS 'Log of gacha pulls per user for history display';
