-- Full website data wipe. The ONLY user data kept is profile achievements.
--
-- KEPT:
--   users                            (accounts, logins, passwords)
--   profile_achievement_definitions  (staff-defined achievement list)
--   profile_achievement_grants       (who earned what)
--   config tables: gacha pools/rewards, battle_restrictions_config,
--                  tournament_prediction_settings, and the settings rows in
--                  cobble_ranked_snapshots (site maintenance, leaderboard display)
--
-- WIPED: wallets + ledgers, inventory, gacha history, shop purchases, reward
--   claims, PvP ranks and payouts, saved teams, public profile bio/avatar,
--   verification and role requests, battle pass grants, presence, ranked
--   replays/results/feed reviews/staff events, predictions, tournaments,
--   and the whole clan system.
--
-- !! TAKE A BACKUP FIRST !! Supabase Dashboard -> Database -> Backups.
-- This cannot be undone.
--
-- Run in the Supabase SQL Editor.

-- ---------------------------------------------------------------------------
-- STEP 0 — list every table so anything not covered below shows up.
-- Read-only. If you see a table here that is not in STEP 2 and is not one of
-- the KEPT tables above, tell me and I will add it.
-- ---------------------------------------------------------------------------

SELECT c.relname AS table_name, c.reltuples::bigint AS approx_rows
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public' AND c.relkind = 'r'
ORDER BY c.relname;

-- ---------------------------------------------------------------------------
-- STEP 1 — sanity check: achievements must survive. Note these numbers.
-- ---------------------------------------------------------------------------

SELECT 'users' AS keeping, count(*) FROM users
UNION ALL SELECT 'achievement_definitions', count(*) FROM profile_achievement_definitions
UNION ALL SELECT 'achievement_grants', count(*) FROM profile_achievement_grants;

-- ---------------------------------------------------------------------------
-- STEP 2 — the wipe.
-- ---------------------------------------------------------------------------

BEGIN;

-- Skips tables that do not exist so a dropped table cannot abort the wipe.
DO $$
DECLARE
  t text;
  targets text[] := ARRAY[
    -- currency history (balances handled separately below)
    'user_cobbledollar_ledger',
    'user_ticket_currency_ledger',
    -- items, gacha, shop, reward claims
    'user_inventory',
    'user_gacha_pulls',
    'user_pokemon_shop_purchases',
    'user_daily_login_claims',
    'user_pvp_daily_payouts',
    -- pvp / profile / requests
    'user_pvp_ranks',
    'user_saved_teams',
    'user_public_profiles',
    'user_verification_requests',
    'user_role_grant_requests',
    'battlepass_lp_grants',
    'minecraft_player_presence',
    -- ranked mirror + moderation
    'cobble_ranked_battle_replays',
    'cobble_ranked_match_results',
    'cobble_ranked_feed_reviews',
    'ranked_battle_staff_events',
    'pvp_top_predictions',
    -- clans (CASCADE covers every child table, listed for clarity)
    'clans',
    'clan_members',
    'clan_join_requests',
    'clan_donations',
    'clan_disbursements',
    'clan_xp_grants',
    'clan_admin_xp_grants',
    'clan_member_leaves',
    'clan_daily_member_income_payouts',
    'clan_leaderboard_daily_payouts'
  ];
BEGIN
  FOREACH t IN ARRAY targets LOOP
    IF to_regclass('public.' || t) IS NOT NULL THEN
      EXECUTE format('TRUNCATE TABLE public.%I RESTART IDENTITY CASCADE', t);
    END IF;
  END LOOP;
END $$;

-- Tournaments use DELETE, not TRUNCATE: TRUNCATE ... CASCADE would also wipe
-- tournament_prediction_settings, which holds admin config we want to keep.
-- DELETE lets the ON DELETE SET NULL / CASCADE rules do the right thing.
DELETE FROM tournaments;

-- Zero every wallet (Cobble$, all ticket types, gems…). Rows are kept so
-- existing accounts keep their wallet rows.
UPDATE user_currency
SET balance = 0,
    updated_at = now()
WHERE balance <> 0;

-- Ranked mirror snapshots are regenerated by the next CobbleRanked sync.
-- Only the data keys are removed; website settings keys stay.
DELETE FROM cobble_ranked_snapshots
WHERE snapshot_key IN ('leaderboard', 'usage_stats');

COMMIT;

-- ---------------------------------------------------------------------------
-- STEP 3 — verify. Achievements must be unchanged, everything else 0.
-- ---------------------------------------------------------------------------

SELECT 'achievement_grants (must be unchanged)' AS check, count(*) AS count
FROM profile_achievement_grants
UNION ALL SELECT 'users (must be unchanged)', count(*) FROM users
UNION ALL SELECT 'wallets holding money', count(*) FROM user_currency WHERE balance <> 0
UNION ALL SELECT 'cobbledollar_ledger', count(*) FROM user_cobbledollar_ledger
UNION ALL SELECT 'ticket_ledger', count(*) FROM user_ticket_currency_ledger
UNION ALL SELECT 'inventory', count(*) FROM user_inventory
UNION ALL SELECT 'gacha_pulls', count(*) FROM user_gacha_pulls
UNION ALL SELECT 'shop_purchases', count(*) FROM user_pokemon_shop_purchases
UNION ALL SELECT 'daily_login_claims', count(*) FROM user_daily_login_claims
UNION ALL SELECT 'battlepass_grants', count(*) FROM battlepass_lp_grants
UNION ALL SELECT 'saved_teams', count(*) FROM user_saved_teams
UNION ALL SELECT 'public_profiles', count(*) FROM user_public_profiles
UNION ALL SELECT 'pvp_ranks', count(*) FROM user_pvp_ranks
UNION ALL SELECT 'tournaments', count(*) FROM tournaments
UNION ALL SELECT 'clans', count(*) FROM clans;

-- ---------------------------------------------------------------------------
-- OPTIONAL — NOT run by default. Read the warnings before uncommenting.
-- ---------------------------------------------------------------------------

-- (A) Reset purchased ranks on the website.
--     WARNING: ranks were bought with real money, and this only clears the
--     website mirror — the LuckPerms group stays on the Minecraft server, so
--     the site and the game would disagree until the server side is reset too.
-- UPDATE users SET minecraft_role = 'member';

-- (B) Clear staff verification + Team AI cooldown.
-- UPDATE users SET minecraft_verified_at = NULL, last_team_ai_at = NULL;

-- (C) Delete uploaded avatar files. Row data is already gone with
--     user_public_profiles; this removes the files from storage.
-- DELETE FROM storage.objects WHERE bucket_id = 'avatars';
